export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST_ORDER = 'FETCH_POST_ORDER'
export const FETCH_SORT_ACTION = 'FETCH_SORT_ACTION'
export const FETCH_POST_REORDER = 'FETCH_POST_REORDER'
